"""user aritcle relationship2

Revision ID: 173621dec865
Revises: a47ec0add770
Create Date: 2019-02-04 20:59:26.118964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173621dec865'
down_revision = 'a47ec0add770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('post_time', sa.DateTime(), nullable=False))
    op.add_column('article', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'user_id')
    op.drop_column('article', 'post_time')
    op.drop_column('article', 'last_modified')
    # ### end Alembic commands ###
