"""add image model 2

Revision ID: 793956d303e2
Revises: 
Create Date: 2019-02-07 15:28:37.721951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793956d303e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('local_path', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
