"""img model added

Revision ID: 8344000b41fa
Revises: 
Create Date: 2019-02-09 08:48:35.620846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8344000b41fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('local_path', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_path')
    )
    op.create_table('article',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=40), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('image')
    op.drop_table('category')
    # ### end Alembic commands ###
