"""section model added

Revision ID: b08d28f182e0
Revises: 173621dec865
Create Date: 2019-02-04 22:10:57.230067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08d28f182e0'
down_revision = '173621dec865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.add_column('article', sa.Column('section_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'article', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'section_id')
    op.drop_table('section')
    # ### end Alembic commands ###
